In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E-commerce data.csv")

In [3]:
df

,Row ID,Ship Mode,Customer ID,Segment,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,849,Standard Class,GA-14725,Consumer,Lorain,Ohio,44052,East,Furniture,Furnishings,48.896,4,0.2,8.5568
1,4010,Standard Class,SC-20725,Consumer,Los Angeles,California,90036,West,Furniture,Furnishings,474.430,11,0.0,199.2606
2,6683,First Class,DP-13390,Home Office,Franklin,Wisconsin,53132,Central,Office Supplies,Binders,3.600,2,0.0,1.7280
3,8070,Standard Class,JM-15250,Consumer,Huntsville,Texas,77340,Central,Office Supplies,Storage,454.560,5,0.2,-107.9580
4,8071,Standard Class,JM-15250,Consumer,Huntsville,Texas,77340,Central,Furniture,Furnishings,141.420,5,0.6,-187.3815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,908,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Technology,Phones,90.930,7,0.0,2.7279
3308,909,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Office Supplies,Binders,52.776,3,0.2,19.7910
3309,1297,Standard Class,EB-13975,Corporate,Fairfield,California,94533,West,Office Supplies,Binders,13.904,2,0.2,4.5188
3310,1298,Standard Class,EB-13975,Corporate,Fairfield,California,94533,West,Office Supplies,Binders,20.720,2,0.2,6.4750
3311,5092,Standard Class,JM-15580,Consumer,Loveland,Colorado,80538,West,Office Supplies,Fasteners,3.024,3,0.2,-0.6048

In [4]:
sums = df.groupby('State')['Sales'].sum()

In [5]:
top3 = df.groupby('State')['Sales'].sum().sort_values(ascending=False)[0:3].index
top3

Index(['California', 'New York', 'Washington'], dtype='object', name='State')

In [6]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [7]:
value_list = ['California', 'New York', 'Washington']
boolean_series = df['State'].isin(value_list)
filtered_df = df[boolean_series]
filtered_df

,Row ID,Ship Mode,Customer ID,Segment,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
1,4010,Standard Class,SC-20725,Consumer,Los Angeles,California,90036,West,Furniture,Furnishings,474.430,11,0.0,199.2606
17,9686,Second Class,FW-14395,Corporate,Los Angeles,California,90032,West,Technology,Accessories,16.590,1,0.0,5.8065
18,5258,Standard Class,DL-13315,Consumer,Rancho Cucamonga,California,91730,West,Office Supplies,Paper,38.880,6,0.0,18.6624
19,9491,Standard Class,CM-12385,Consumer,San Francisco,California,94110,West,Office Supplies,Binders,2022.272,8,0.2,682.5168
20,9492,Standard Class,CM-12385,Consumer,San Francisco,California,94110,West,Office Supplies,Art,9.120,3,0.0,3.1008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,907,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Furniture,Bookcases,323.136,4,0.2,12.1176
3307,908,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Technology,Phones,90.930,7,0.0,2.7279
3308,909,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Office Supplies,Binders,52.776,3,0.2,19.7910
3309,1297,Standard Class,EB-13975,Corporate,Fairfield,California,94533,West,Office Supplies,Binders,13.904,2,0.2,4.5188
3310,1298,Standard Class,EB-13975,Corporate,Fairfield,California,94533,West,Office Supplies,Binders,20.720,2,0.2,6.4750

In [8]:
categories = filtered_df.groupby('Category')['Sales'].sum()
categories

Category
Furniture           82834.8915
Office Supplies     99134.5240
Technology         123881.8200
Name: Sales, dtype: float64

In [9]:
filtered_df = filtered_df[filtered_df['Category'] == 'Technology']
filtered_df

,Row ID,Ship Mode,Customer ID,Segment,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
17,9686,Second Class,FW-14395,Corporate,Los Angeles,California,90032,West,Technology,Accessories,16.590,1,0.0,5.8065
79,1659,Standard Class,TH-21100,Consumer,Los Angeles,California,90045,West,Technology,Phones,160.776,3,0.2,10.0485
81,2409,Standard Class,TM-21010,Consumer,San Francisco,California,94122,West,Technology,Phones,359.976,3,0.2,130.4913
85,734,Standard Class,DS-13030,Home Office,Seattle,Washington,98115,West,Technology,Accessories,179.970,3,0.0,86.3856
108,6360,Standard Class,CS-12250,Corporate,Seattle,Washington,98103,West,Technology,Phones,86.352,6,0.2,8.6352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3206,8178,First Class,CM-12115,Consumer,Los Angeles,California,90008,West,Technology,Accessories,474.950,5,0.0,142.4850
3237,4620,First Class,RM-19675,Home Office,Los Angeles,California,90049,West,Technology,Copiers,2879.952,6,0.2,1007.9832
3278,574,Standard Class,JF-15415,Consumer,New York City,New York,10024,East,Technology,Phones,14.850,3,0.0,4.0095
3294,1879,Standard Class,JG-15160,Consumer,Los Angeles,California,90049,West,Technology,Phones,302.376,3,0.2,22.6782
3307,908,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Technology,Phones,90.930,7,0.0,2.7279

In [10]:
subcats = filtered_df.groupby('Sub-Category')['Sales'].sum()
subcats

Sub-Category
Accessories    27441.120
Copiers        37659.694
Machines       22972.746
Phones         35808.260
Name: Sales, dtype: float64

In [12]:
quantity_df = df[df['Region'] == "East"]
quantity_df

,Row ID,Ship Mode,Customer ID,Segment,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,849,Standard Class,GA-14725,Consumer,Lorain,Ohio,44052,East,Furniture,Furnishings,48.896,4,0.2,8.5568
29,7221,Standard Class,BP-11290,Consumer,Philadelphia,Pennsylvania,19140,East,Office Supplies,Binders,274.491,3,0.7,-228.7425
30,1846,Second Class,DA-13450,Home Office,Washington,District of Columbia,20016,East,Office Supplies,Paper,40.080,6,0.0,19.2384
31,1847,Second Class,DA-13450,Home Office,Washington,District of Columbia,20016,East,Furniture,Furnishings,37.680,2,0.0,15.8256
56,2767,First Class,RW-19690,Consumer,Philadelphia,Pennsylvania,19134,East,Office Supplies,Appliances,34.384,1,0.2,3.8682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,574,Standard Class,JF-15415,Consumer,New York City,New York,10024,East,Technology,Phones,14.850,3,0.0,4.0095
3295,2875,First Class,MC-17845,Consumer,New York City,New York,10035,East,Office Supplies,Fasteners,6.030,3,0.0,2.9547
3306,907,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Furniture,Bookcases,323.136,4,0.2,12.1176
3307,908,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Technology,Phones,90.930,7,0.0,2.7279
3308,909,Standard Class,PO-18865,Consumer,New York City,New York,10009,East,Office Supplies,Binders,52.776,3,0.2,19.7910

In [15]:
quantity_df['Quantity'].unique()

array([ 4,  3,  6,  2,  1,  8,  9,  5,  7, 14, 10, 11, 13, 12])

In [16]:
quantity_df['Discount'].unique()

array([0.2, 0.7, 0. , 0.4, 0.3, 0.1, 0.5])

In [17]:
df['Region'].unique()

array(['East', 'West', 'Central', 'South'], dtype=object)